Version1
graasp/graasp-app-excalidraw pull request #3
Opened 2022-12-09 07:50 UTC by lgodier

2022-12-12 10:22 UTC, swouf requested changes
Thank you for this nice first PR!

I asked for a lot of small changes. Please, review as many of them as you can and don't hesitate to ask me questions, either by directly answering my comments or sending me an email. We can also set up a meeting.

The most important comments are the ones on the code that you wrote and that should be taken into account by the end of the project. Try to focus on these then.

And don't be afraid of the number of comments, it is a lot of small things and in general, the code is good.

2022-12-12 10:22 UTC, swouf commented on src/components/Excalidraw.tsx
> +      type: 'session',
To set the type, use the `APP_DATA_TYPES` enum.

2022-12-12 10:22 UTC, swouf commented on src/components/views/read/PlayerView.tsx
> +import { RecordOf } from 'immutable';
If you don't use the PlayerView, delete this file.

2022-12-12 10:22 UTC, swouf commented on src/config/selectors.ts
> +export const SETTING_VALUE_FIELD_CY = 'setting_value_field';
These selectors are used for tests. Delete those that you don't use (I guess it will be most of them if not all).

2022-12-12 10:22 UTC, swouf commented on src/data/db.ts
> +    },
Remove this mock app data if you don't use them.

2022-12-12 10:22 UTC, swouf commented on src/data/db.ts
> +  ],
Remove this app setting if it is not useful.

2022-12-12 10:22 UTC, swouf commented on src/langs/fr.json
> +    "Members": "Membres"
Adapt translations. You can do that later if you want (then turn this comment into an issue).

2022-12-12 15:45 UTC, swouf commented on README.md
> +# Graasp App Template Typescript
In the end, I already converted it into an issue. See #4

2022-12-13 10:25 UTC, lgodier commented on cypress/e2e/player/read/showApp.cy.ts
> +import { Context, PermissionLevel } from '@graasp/sdk';
done

2022-12-13 12:26 UTC, lgodier commented on src/components/Excalidraw.tsx
> +          height: '800px',
We did it that way because using percentage didn't work at the beginning. Tried again and should be fine.

2022-12-14 09:26 UTC, swouf requested changes
There are missing files.

2022-12-14 12:34 UTC, swouf requested changes
Probably last changes I will request. Good work !

2022-12-14 12:34 UTC, swouf commented on src/components/InitialData.ts
> +import { init } from 'i18next';
You don't use this import, right?

2022-12-14 12:34 UTC, swouf commented on src/components/InitialData.ts
> +const getInitialData = (elements: any, state: any): ImportedDataState => {
I imagine that Excalidraw provides a type for a collection of elements as well as for the state. Try to use it.

2022-12-14 14:21 UTC, lgodier commented
done with these new changes

2022-12-16 12:01 UTC, merged